IF EXISTS (SELECT name FROM master.sys.databases WHERE name = N'PHP_API')
BEGIN
	DROP DATABASE [PHP_API];
END

/****** Object:  Database [PHP_API]    Script Date: 23.09.2022 11:24:55 ******/
CREATE DATABASE [PHP_API]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PHP_API', FILENAME = N'U:\MSSQL\DATA\PHP_API.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PHP_API_LOG', FILENAME = N'U:\MSSQL\DATA\PHP_API_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [PHP_API] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PHP_API].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PHP_API] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PHP_API] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PHP_API] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PHP_API] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PHP_API] SET ARITHABORT OFF 
GO
ALTER DATABASE [PHP_API] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PHP_API] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PHP_API] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PHP_API] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PHP_API] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PHP_API] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PHP_API] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PHP_API] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PHP_API] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PHP_API] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PHP_API] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PHP_API] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PHP_API] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PHP_API] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PHP_API] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PHP_API] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PHP_API] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PHP_API] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PHP_API] SET  MULTI_USER 
GO
ALTER DATABASE [PHP_API] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PHP_API] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PHP_API] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PHP_API] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [PHP_API] SET DELAYED_DURABILITY = DISABLED 
GO
USE [PHP_API]
GO
/****** Object:  Table [dbo].[Künstler]    Script Date: 23.09.2022 11:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Künstler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Künstler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[KünstlerCollection]    Script Date: 23.09.2022 11:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KünstlerCollection](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[KünstlerId] [int] NOT NULL,
	[MusikträgerId] [int] NOT NULL,
 CONSTRAINT [PK_KünstlerCollection] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Lokation]    Script Date: 23.09.2022 11:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lokation](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Regal] [int] NULL,
	[Etage] [int] NULL,
	[Stelle] [int] NULL,
	[Active] [bit] NULL,
 CONSTRAINT [PK_Lokation] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Medium]    Script Date: 23.09.2022 11:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medium](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[B-Seite] [bit] NULL,
	[LocationId] [int] NULL,
 CONSTRAINT [PK_Medium] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Mediumcollection]    Script Date: 23.09.2022 11:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mediumcollection](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
	[MusikträgerId] [int] NOT NULL,
	[MediumId] [int] NOT NULL,
	[TitelcollectionId] [int] NULL,
 CONSTRAINT [PK_Mediumcollection] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UIX_Mediumcollection_Type_MusikträgerId_MediumId_TitelcollectionId] UNIQUE NONCLUSTERED 
(
	[Type] ASC,
	[MediumId] ASC,
	[MusikträgerId] ASC,
	[TitelcollectionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Musikträger]    Script Date: 23.09.2022 11:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Musikträger](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Genre] [nvarchar](50) NOT NULL,
	[Kaufdatum] [date] NOT NULL,
 CONSTRAINT [PK_Musikträger] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Titel]    Script Date: 23.09.2022 11:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Titel](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Titel] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Titelcollection]    Script Date: 23.09.2022 11:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Titelcollection](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TitelId] [int] NOT NULL,
	[KünstlerId] [int] NOT NULL,
 CONSTRAINT [PK_Titelcollection] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[KünstlerCollection]  WITH CHECK ADD  CONSTRAINT [FK_KünstlerCollection_Künstler] FOREIGN KEY([KünstlerId])
REFERENCES [dbo].[Künstler] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[KünstlerCollection] CHECK CONSTRAINT [FK_KünstlerCollection_Künstler]
GO
ALTER TABLE [dbo].[KünstlerCollection]  WITH CHECK ADD  CONSTRAINT [FK_KünstlerCollection_Musikträger] FOREIGN KEY([MusikträgerId])
REFERENCES [dbo].[Musikträger] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[KünstlerCollection] CHECK CONSTRAINT [FK_KünstlerCollection_Musikträger]
GO
ALTER TABLE [dbo].[Medium]  WITH CHECK ADD  CONSTRAINT [FK_Medium_Lokation] FOREIGN KEY([LocationId])
REFERENCES [dbo].[Lokation] ([Id])
GO
ALTER TABLE [dbo].[Medium] CHECK CONSTRAINT [FK_Medium_Lokation]
GO
ALTER TABLE [dbo].[Mediumcollection]  WITH CHECK ADD  CONSTRAINT [FK_Mediumcollection_Medium] FOREIGN KEY([MediumId])
REFERENCES [dbo].[Medium] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Mediumcollection] CHECK CONSTRAINT [FK_Mediumcollection_Medium]
GO
ALTER TABLE [dbo].[Mediumcollection]  WITH CHECK ADD  CONSTRAINT [FK_Mediumcollection_Musikträger] FOREIGN KEY([MusikträgerId])
REFERENCES [dbo].[Musikträger] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Mediumcollection] CHECK CONSTRAINT [FK_Mediumcollection_Musikträger]
GO
ALTER TABLE [dbo].[Mediumcollection]  WITH CHECK ADD  CONSTRAINT [FK_Mediumcollection_Titelcollection] FOREIGN KEY([TitelcollectionId])
REFERENCES [dbo].[Titelcollection] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Mediumcollection] CHECK CONSTRAINT [FK_Mediumcollection_Titelcollection]
GO
ALTER TABLE [dbo].[Titelcollection]  WITH CHECK ADD  CONSTRAINT [FK_Titelcollection_Künstler] FOREIGN KEY([KünstlerId])
REFERENCES [dbo].[Künstler] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Titelcollection] CHECK CONSTRAINT [FK_Titelcollection_Künstler]
GO
ALTER TABLE [dbo].[Titelcollection]  WITH CHECK ADD  CONSTRAINT [FK_Titelcollection_Titel] FOREIGN KEY([TitelId])
REFERENCES [dbo].[Titel] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Titelcollection] CHECK CONSTRAINT [FK_Titelcollection_Titel]
GO
ALTER DATABASE [PHP_API] SET  READ_WRITE 
GO
