INSERT INTO Titel VALUES('TestTitel')
INSERT INTO Titel VALUES('TestTitel1')
INSERT INTO [Künstler] VALUES('TestKünstler')
INSERT INTO [Künstler] VALUES('TestKünstler1')
INSERT INTO Titelcollection VALUES((SELECT MAX(Id) FROM Titel) - 1, (SELECT MAX(Id) FROM [Künstler]) - 1)
INSERT INTO Titelcollection VALUES((SELECT MAX(Id) FROM Titel), (SELECT MAX(Id) FROM [Künstler]))
INSERT INTO [Musikträger] VALUES('TestMT', 'TestGenre', GETDATE())
INSERT INTO [Musikträger] VALUES('TestMT1', 'TestGenre', '04.04.1944')
INSERT INTO [Musikträger] VALUES('TestMT2', 'TestGenre', '01.01.1901')
INSERT INTO [KünstlerCollection] VALUES((SELECT MAX(Id) FROM [Künstler]) - 1, (SELECT MAX(Id) FROM [Musikträger]) - 2)
INSERT INTO [KünstlerCollection] VALUES((SELECT MAX(Id) FROM [Künstler]), (SELECT MAX(Id) FROM [Musikträger]) - 1)
INSERT INTO [KünstlerCollection] VALUES((SELECT MAX(Id) FROM [Künstler]), (SELECT MAX(Id) FROM [Musikträger]))
INSERT INTO Lokation VALUES(1, 1, 1, 1)
INSERT INTO [Medium] VALUES(0, (SELECT MAX(Id) FROM Lokation))
INSERT INTO [Medium] VALUES(1, NULL)
INSERT INTO [Medium] VALUES(0, NULL)
INSERT INTO Mediumcollection VALUES ('TestType', (SELECT MAX(Id) FROM [Musikträger]), (SELECT MAX(Id) FROM [Medium]) - 1, NULL)
INSERT INTO Mediumcollection VALUES ('TestType1', (SELECT MAX(Id) FROM [Musikträger]), (SELECT MAX(Id) FROM [Medium]) - 1, (SELECT MAX(Id) FROM Titelcollection) - 1)
INSERT INTO Mediumcollection VALUES ('TestType2', (SELECT MAX(Id) FROM [Musikträger]), (SELECT MAX(Id) FROM [Medium]), (SELECT MAX(Id) FROM Titelcollection))